function C = C_func(in1,in2)
%C_func
%    C = C_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    09-Nov-2025 12:18:59

C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
