function M = M_func(in1,in2)
%M_func
%    M = M_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    09-Nov-2025 12:18:58

M = reshape([4.53e+2./5.0e+1,0.0,0.0,0.0,4.53e+2./5.0e+1,0.0,0.0,0.0,9.03e+2./1.0e+2],[3,3]);
end
